#include <QtTest>

#include "core/migration.h"
#include "core/preferences.h"
#include "core/themestate.h"
#include "testenv.h"

class TstMigration : public QObject
{
    Q_OBJECT
private slots:
    void mapsNwgLookPreferences()
    {
        const QByteArray json = R"({
            "export-settings-ini": false,
            "export-gtkrc-20": false,
            "export-index-theme": true,
            "export-xsettingsd": false,
            "export-gtk4-symlinks": true,
            "flatpak-export-gtk-theme-override": true,
            "flatpak-export-icon-theme-override": false,
            "flatpak-install-current-gtk-theme": true
        })";
        Preferences p;
        const QStringList applied = Migration::applyNwgLookJson(json, &p, true);
        QCOMPARE(applied.size(), 8);
        QVERIFY(!p.exportSettingsIni);
        QVERIFY(!p.exportGtkrc2);
        QVERIFY(p.exportIndexTheme);
        QVERIFY(!p.exportXsettingsd);
        QVERIFY(p.exportGtk4Symlinks);
        QVERIFY(p.flatpakGtkThemeOverride);
        QVERIFY(p.flatpakInstallCurrentTheme);
    }

    void gtk4SymlinksAreNotImportedInAKineticWeSession()
    {
        Preferences p;   // exportGtk4Symlinks defaults to off
        Migration::applyNwgLookJson(R"({"export-gtk4-symlinks": true})", &p, false);
        QVERIFY(!p.exportGtk4Symlinks);
    }

    void ignoresMalformedJson()
    {
        Preferences p;
        QVERIFY(Migration::applyNwgLookJson("not json", &p, true).isEmpty());
        QVERIFY(Migration::applyNwgLookJson(R"({"export-gtkrc-20": "yes"})", &p, true).isEmpty());   // wrong type
        QVERIFY(p.exportGtkrc2);
    }

    void runsOnceAndCopiesTheBackup()
    {
        TestEnv env;
        TestEnv::write(env.path(".config/nwg-look/config"), R"({"export-xsettingsd": false})");
        TestEnv::write(env.path(".local/share/nwg-look/gsettings"), "gtk-theme=Nordic\ncursor-size=32\n");

        QVERIFY(Migration::needed());
        Preferences p = Prefs::load();
        const Migration::Report r = Migration::run(&p);
        QVERIFY(r.ran);
        QVERIFY(!Prefs::load().exportXsettingsd);
        QVERIFY(QFileInfo::exists(ThemeStateIO::backupPath()));
        QVERIFY(!Migration::needed());   // once
    }

    void neverOverwritesAnExistingBackup()
    {
        TestEnv env;
        TestEnv::write(env.path(".local/share/nwg-look/gsettings"), "gtk-theme=Old\n");
        TestEnv::write(ThemeStateIO::backupPath(), "gtk-theme=Mine\n");
        Preferences p;
        Migration::run(&p);
        QCOMPARE(TestEnv::read(ThemeStateIO::backupPath()), QString("gtk-theme=Mine\n"));
    }

    void nothingToMigrateWithoutNwgLook()
    {
        TestEnv env;
        QVERIFY(!Migration::needed());
    }

    void backupRoundTrip()
    {
        TestEnv env;
        ThemeState s;
        s.gtkTheme = "Nordic";
        s.iconTheme = "Papirus";
        s.fontName = "Noto Sans 11";
        s.cursorTheme = "Bibata";
        s.cursorSize = 32;
        s.textScalingFactor = 1.25;
        s.colorScheme = "prefer-dark";
        s.eventSounds = false;
        s.inputFeedbackSounds = true;
        QVERIFY(ThemeStateIO::saveBackup(s, nullptr));

        ThemeState back;
        QVERIFY(ThemeStateIO::loadBackup(ThemeStateIO::backupPath(), &back));
        QVERIFY(back == s);
    }

    void backupUsesNwgLooksFormat()
    {
        TestEnv env;
        ThemeState s;
        QVERIFY(ThemeStateIO::saveBackup(s, nullptr));
        const QString text = TestEnv::read(ThemeStateIO::backupPath());
        QVERIFY(text.startsWith("# Generated by"));
        QVERIFY(text.contains("gtk-theme=Adwaita\n"));
        QVERIFY(text.contains("event-sounds=true\n"));
        QVERIFY(text.contains("input-feedback-sounds=false\n"));
    }

    void preferencesRoundTripAndWindowStateStayInTheAppDir()
    {
        TestEnv env;
        Preferences p;
        p.exportGtk4Symlinks = true;
        p.linkQt = false;
        QVERIFY(Prefs::save(p, nullptr));
        QVERIFY(Prefs::load() == p);

        Prefs::saveWindowGeometry("geom");
        QCOMPARE(Prefs::loadWindowGeometry(), QByteArray("geom"));
        // The window geometry must never land in qt5ct.conf / qt6ct.conf (plugin reload storm).
        QVERIFY(Prefs::filePath().contains("/lgl-kwe-look/"));
        QVERIFY(!QFileInfo::exists(env.path(".config/qt6ct/qt6ct.conf")));
    }
};

QTEST_MAIN(TstMigration)
#include "tst_migration.moc"
